# Generated by Django 2.1.1 on 2019-02-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='areacode',
        ),
    ]
